spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: QzQXX4475mFlhHG3ycZ8BXEtjA8H4NxN
            client-secret: wRXgyveOXdE-QTQUfqOEphasTnPZIaa4ayxYtfChZGyVjT7b4asfHU5vNxB4n2lP
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important
            issuer-uri: https://dev-k7bf43hu.us.auth0.com/

  datasource:
    password: Dk@jE4BUWie7AL8
    url: jdbc:postgresql://db.txdowoqnrtqpodkhwiqr.supabase.co:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: yyyy-MM-dd